# Generated by Django 4.1.4 on 2022-12-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBPSRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_id', models.CharField(max_length=64)),
                ('account_id', models.IntegerField()),
                ('year', models.CharField(max_length=64)),
                ('month', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('DUE', 'DUE')], max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('principal_outstanding_amount', models.FloatField()),
                ('foreclosure_amount', models.FloatField()),
                ('outstanding_amount', models.FloatField()),
            ],
        ),
    ]
