# Generated by Django 4.1.4 on 2022-12-22 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BBPSRepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lender_id", models.CharField(max_length=64)),
                ("account_id", models.CharField(max_length=16)),
                ("loan_id", models.CharField(max_length=64)),
                ("year", models.CharField(max_length=64)),
                ("month", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=64)),
                ("due_date", models.DateField()),
                ("principal_outstanding_amount", models.FloatField()),
                ("foreclosure_amount", models.FloatField()),
                ("outstanding_amount", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
